{
imports = [
./brave.nix
./wm/hyprland/hyprland.nix
./wm/input/nihongo.nix
./style/networkmanager-dmenu.nix
./style/stylix.nix
./shell/sh.nix
./shell/git.nix
./shell/lvim.nix
./shell/tmux.nix
./shell/kitty.nix
./security/sops.nix
./security/keepass.nix
./hardware/kanshi.nix
./hardware/bluetooth.nix
./hardware/virtualization.nix
./lang
];
}
